import { Lexend } from "next/font/google";
import { ChakraProvider } from '@chakra-ui/react'

const inter = Lexend({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (

    <html lang="en">
      <ChakraProvider>
      <body className={inter.className}>{children}</body>
      </ChakraProvider>
    </html>
  );
}
